version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/packaging/docker"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/.buildkite"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
