version: '2.1'

services:
  agent:
    command: "buildkite-agent start --endpoint http://agent.buildkite.dev/v3"
    environment:
      BUILDKITE_AGENT_TAGS: queue=default
      BUILDKITE_AGENT_TOKEN: test
      BUILDKITE_BUILD_PATH: /buildkite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: buildkite_default