version: '3.5'

services:
  agent:
    image: golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59
    volumes:
      - ../:/work:cached
    working_dir: /work
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"

  ruby:
    image: ruby:2.6
    volumes:
      - ..:/work
      - ruby-2-6-agent-gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash
    environment:
      - FULL_AGENT_VERSION
      - AGENT_VERSION
      - BUILD_VERSION

volumes:
  ruby-2-6-agent-gem-cache: ~
