version: '3.5'

services:
  agent:
    image: golang:1.14@sha256:b451547e2056c6369bbbaf5a306da1327cc12c074f55c311f6afe3bfc1c286b6
    volumes:
      - ../:/work:cached
    working_dir: /work
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"

  ruby:
    image: ruby:2.6
    volumes:
      - ..:/work
      - ruby-2-6-agent-gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash
    environment:
      - FULL_AGENT_VERSION
      - AGENT_VERSION
      - BUILD_VERSION

volumes:
  ruby-2-6-agent-gem-cache: ~
