version: '3.5'

services:
  agent:
    image: golang:1.14@sha256:174e1be71bd2aa8c65d6c17be0e5c0f8bc4e4ec03e82a5f57aad0b8acf22ef7f
    volumes:
      - ../:/work:cached
    working_dir: /work
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"

  ruby:
    image: ruby:2.6
    volumes:
      - ..:/work
      - ruby-2-6-agent-gem-cache:/usr/local/bundle
    working_dir: /work
    command: /bin/bash
    environment:
      - FULL_AGENT_VERSION
      - AGENT_VERSION
      - BUILD_VERSION

volumes:
  ruby-2-6-agent-gem-cache: ~
