steps:

  - wait

  - name: ":docker: :package:"
    plugins:
      docker-compose#e8ce6c1:
        build: agent
        image-repository: index.docker.io/buildkiteci/agent
    agents:
      queue: elastic-builders

  - wait

  -
    name: "🔨"
    command: "scripts/tests.sh"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  -
    name: "📦"
    command: "scripts/build-binaries.sh"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - wait

  -
    name: ":debian: build"
    command: "scripts/build-debian-packages.sh"
    artifact_paths: "deb/**/*"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":redhat: experimental"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish experimental"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":github: :hammer:"
    command: "scripts/build-github-release.sh"
    artifact_paths: "releases/**/*"
    branches: "master 2-1-stable"
    plugins:
      docker-compose#e8ce6c1:
        run: agent

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - block: ":shipit: Unstable"
    branches: "master 2-1-stable"

  -
    name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  -
    name: ":octocat: :rocket:"
    command: "scripts/github-release.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish unstable"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  -
    name: ":beer:"
    command: "scripts/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"

  - block: ":shipit: Stable"
    branches: "master 2-1-stable"

  -
    name: ":s3: publish binaries"
    command: "scripts/publish-to-s3.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master 2-1-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish stable"
    command: "scripts/publish-debian-package.sh"
    branches: "master 2-1-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master 2-1-stable"
    agents:
      queue: "deploy"
