steps:
  - wait

  - name: ":spiral_note_pad:"
    command: "scripts/check-changelog.sh"

  - wait

  - name: ":s3:"
    command: "scripts/publish-to-s3.sh"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - name: ":octocat: :rocket:"
    command: "scripts/github-release.sh"
    agents:
      queue: "deploy"

  - name: ":redhat:"
    command: "scripts/publish-rpm-package.sh"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - name: ":debian:"
    command: "scripts/publish-debian-package.sh"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - name: ":docker:"
    command: "scripts/publish-docker-images.sh"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - wait

  - name: ":beer:"
    command: "scripts/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    agents:
      queue: "deploy"

